# Generated by Django 2.2 on 2019-08-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='some default name', max_length=120)),
                ('abilities', models.CharField(blank=True, max_length=120, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('flavor_text', models.TextField(blank=True, null=True)),
                ('card_number', models.PositiveIntegerField(default=0, max_length=120)),
                ('artist', models.CharField(default='some magic artist', max_length=120)),
                ('spell_type', models.CharField(choices=[('CR', 'Creature'), ('PL', 'Planeswalker'), ('IN', 'Instant'), ('SO', 'Sorcery'), ('EN', 'Enchantment'), ('AR', 'Artifact')], default='CR', max_length=2)),
            ],
        ),
    ]
