# Generated by Django 2.2 on 2019-08-17 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
