# Generated by Django 2.2 on 2019-08-13 21:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_auto_20190813_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='year_in_school',
        ),
        migrations.AddField(
            model_name='card',
            name='spell_type',
            field=models.CharField(choices=[('CR', 'Creature'), ('PL', 'Planeswalker'), ('IN', 'Instant'), ('SO', 'Sorcery'), ('EN', 'Enchantment'), ('AR', 'Artifact')], default='CR', max_length=2),
            preserve_default=False,
        ),
    ]
