# Generated by Django 2.2 on 2019-08-17 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_auto_20190817_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(default='some default name', max_length=120, unique=True),
        ),
    ]
