# Generated by Django 2.2 on 2019-08-26 17:54

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_auto_20190817_2319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['card_number']},
        ),
        migrations.AddField(
            model_name='card',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='name',
                                                editable=False,
                                                populate_from='name'),
            preserve_default=False,
        ),
    ]
