# Generated by Django 2.2 on 2019-08-15 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_auto_20190815_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='Card_number',
            new_name='Card_Number',
        ),
    ]
