# Generated by Django 2.2 on 2019-08-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_auto_20190815_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='Card_Number',
            field=models.CharField(max_length=120),
        ),
    ]
