# Generated by Django 2.2 on 2019-08-26 17:57

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_auto_20190826_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True,
                                                editable=False,
                                                populate_from='name'),
        ),
    ]
