# Generated by Django 2.2 on 2019-09-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_auto_20190909_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='mana_black',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3),
                                               (4, 4), (5, 5), (6, 6), (7, 7),
                                               (8, 8), (9, 9), (10, 10),
                                               (-1, 'X')],
                                      default=0),
        ),
        migrations.AlterField(
            model_name='card',
            name='mana_blue',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3),
                                               (4, 4), (5, 5), (6, 6), (7, 7),
                                               (8, 8), (9, 9), (10, 10),
                                               (-1, 'X')],
                                      default=0),
        ),
        migrations.AlterField(
            model_name='card',
            name='mana_colorless',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3),
                                               (4, 4), (5, 5), (6, 6), (7, 7),
                                               (8, 8), (9, 9), (10, 10),
                                               (-1, 'X')],
                                      default=0),
        ),
        migrations.AlterField(
            model_name='card',
            name='mana_green',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3),
                                               (4, 4), (5, 5), (6, 6), (7, 7),
                                               (8, 8), (9, 9), (10, 10),
                                               (-1, 'X')],
                                      default=0),
        ),
        migrations.AlterField(
            model_name='card',
            name='mana_red',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3),
                                               (4, 4), (5, 5), (6, 6), (7, 7),
                                               (8, 8), (9, 9), (10, 10),
                                               (-1, 'X')],
                                      default=0),
        ),
        migrations.AlterField(
            model_name='card',
            name='mana_white',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3),
                                               (4, 4), (5, 5), (6, 6), (7, 7),
                                               (8, 8), (9, 9), (10, 10),
                                               (-1, 'X')],
                                      default=0),
        ),
    ]
