# Generated by Django 2.2 on 2019-09-13 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_auto_20190913_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardsInDeck',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('card',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='cards.Card')),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('name', models.CharField(default='Deck Name',
                                          max_length=120)),
                ('cards',
                 models.ManyToManyField(through='cards.CardsInDeck',
                                        to='cards.Card')),
            ],
        ),
        migrations.AddField(
            model_name='cardsindeck',
            name='deck',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='cards.Deck'),
        ),
    ]
