# Generated by Django 2.2 on 2019-09-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0014_auto_20190913_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='defense',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='loyalty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='power',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
