# Generated by Django 2.2 on 2019-09-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0015_auto_20190914_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='expansion',
            field=models.CharField(choices=[('ELD', 'Throne of Eldraine (ELD)')
                                            ],
                                   default='ELD',
                                   max_length=2),
        ),
    ]
