# Generated by Django 2.2 on 2019-09-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0020_auto_20190914_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='mana_bluewhite',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3),
                                               (4, 4), (5, 5), (6, 6), (7, 7),
                                               (8, 8), (9, 9), (10, 10),
                                               (-1, 'X')],
                                      default=0),
        ),
    ]
