# Generated by Django 2.2 on 2019-09-21 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0021_card_mana_bluewhite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mana',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ManaForCard',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('card',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='cards.Card')),
                ('mana',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='cards.Mana')),
            ],
            options={
                'unique_together': {('mana', 'card')},
            },
        ),
        migrations.AddField(
            model_name='card',
            name='mana',
            field=models.ManyToManyField(through='cards.ManaForCard',
                                         to='cards.Mana'),
        ),
    ]
